site_name: QA_Training
repo_url: https://github.com/majitaki4ryu/qa_training
repo_name: majitaki4ryu/qa_training

use_directory_urls: false

nav:
  - ホーム: index.md
  - 要求: requirements.md
  - ドメインモデル: domain_model.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.snippets:
      #check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  #- glightbox
  - drawio-exporter:
      cache_dir: "drawio-exporter"
      drawio_executable: null
      drawio_args: ["--no-sandbox"]
      format: svg
      embed_format: "{img_open}{img_src}{img_close}"
      sources: "*.drawio"