[tool.poetry]
name = "qa-training"
version = "0.1.0"
description = ""
authors = ["majitaki1234@gmail.com"]
readme = "README.md"
packages = [{include = "qa_training"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
