[tool.poetry]
name = "qa-training"
version = "0.1.0"
description = ""
authors = ["maji <majitaki1234@gmail.com>"]
readme = "README.md"
packages = [{include = "qa_training"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
ruff = "^0.0.257"
mkdocs = "^1.4.2"
mkdocs-material = "^9.1.3"
mkdocs-gen-files = "^0.4.0"
mkdocs-literate-nav = "^0.6.0"
mkdocstrings-python-legacy = "^0.2.3"
mkdocs-kroki-plugin = "^0.6.1"
mkdocs-table-reader-plugin = "^2.0"
pytkdocs = "^0.16.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = false